### ISSUE TITLE
Plugin not working with version Kibana 6.1.1

### ISSUE THREAD

**Issue by ilp** [mstoyano/TFG#27]
I already used the plugin on versions 5.x, but I now need to upgrade my Kibana to last version.

**Comment by mrchang7** [comment]
I also hoping this be available soon. 

Did it work in 5.6 though? Nothing shown as another guy reported.

**Comment by octavioranieri** [comment]
The error may be related with these changes on new version, they have changed again the code: https://github.com/elastic/kibana/issues/15844

I receive the following message when trying to install:

    ERROR in ../plugins/k5p-c3/public/c3_vis.js
    Module not found: Error: Can't resolve 'ui/template_vis_type/template_vis_type' in '/opt/kibana/plugins/k5p-c3/public'

    ERROR in ../plugins/k5p-c3/public/c3_vis.js
    Module not found: Error: Can't resolve 'ui/vis/schemas' in '/opt/kibana/plugins/k5p-c3/public'

Can someone take a look on this to have a version for Kibana 6.1.1?

Thank you in advance!

**Comment by thekofimensah** [comment]
I could also use this in 6.X   :D

**Comment by kumar-abhijit** [comment]
Hi @octaavio ,
There are changes happens from Kibana 5x to Kibana 6x. Please use the new path in your js code:
>> import { VisFactoryProvider } from 'ui/vis/vis_factory';
>> import { VisSchemasProvider } from 'ui/vis/editors/default/schemas';

You also need to change the VisualizationRegisteryProvider:
>> import { VisTypesRegistryProvider } from 'ui/registry/vis_types';

Hope this helps.

**Comment by ilp** [comment]
Now is working. I update my js code and works in Kibana 6.x.

**Comment by Narendra2011** [comment]
Hi, 

I am facing an issue if i use this in kibana 6.2.4. After installing the plugin, kibana is not getting started showing this message for sometime :
**Optimizing and caching bundles for state SessionStorageRedirect, status_page, timelion and kibana**

Kibana console showing this message for sometime and getting closed after sometime. can anyone help me with this?

**Comment by thekofimensah** [comment]
just keep waiting! it can take like 10 mins sometimes. if it doesn't work
after that message, what message do you see?

**Comment by kumar-abhijit** [comment]
Hi @seanziee ,

It will keep loading and you need to manually stop the Kibana server from the terminal. It happens because of incorrect plugin installed within Kibana. You can stop the Kibana server and remove the plugin you just install before getting error. It will start working.

Hope this helps.

**Comment by thekofimensah** [comment]
@kumar-abhijit I think you meant to point that to the guy above me. I can make it work :D I was trying to help him as well.

**Comment by Narendra2011** [comment]
Yes @kumar-abhijit i already did that. If i uninstall the plugin, kibana is working perfectly. I am trying to find a way to make the plugin work with 6.2.4. I tried with kibana 5.3.0 and it perfectly worked.

@seanziee in which version you made it working? if it is some 6.0+ could u please help me in achieving the same.....?

**Comment by ilp** [comment]
@Narendra2011 the plugin is working in the version 6.2.4, I did some changes on code, you can to check in [my fork](https://github.com/ilp1995/kbn_c3js_vis/commit/b64888e663bbb263b21b4cb915fc5e381850a3e9).

**Comment by Narendra2011** [comment]
@ilp1995 Thanks for your help. After checking in ur code, i am able to run kibana server, but couldn't find c3 charts on visualization tab.

Could you please check that?

**Comment by Narendra2011** [comment]
@ilp1995 Thanks a lot... Don't know what happened, today it worked like a charm. Really thanks for your time and effort.
